# Generated by Django 4.2 on 2023-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_designationinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
