# Generated by Django 4.2 on 2023-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assests',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assests',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assests',
            name='modified_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='assests',
            name='assests_type',
            field=models.CharField(choices=[('phones', 'Phones'), ('tablets', 'laptops'), ('laptop', 'laptop')], max_length=15),
        ),
    ]
