# Generated by Django 4.2 on 2023-04-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assests', '0002_assests_created_at_assests_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handedoutassests',
            name='return_at',
            field=models.DateField(blank=True),
        ),
    ]
