# Generated by Django 4.2 on 2023-04-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assests', '0003_alter_handedoutassests_return_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handedoutassests',
            name='return_condition',
            field=models.TextField(blank=True),
        ),
    ]
