# Generated by Django 4.2 on 2023-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assests', '0004_alter_handedoutassests_return_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='handedoutassests',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
