# Generated by Django 4.2 on 2023-04-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assests', '0005_handedoutassests_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handedoutassests',
            name='return_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
